### ISSUE TITLE
some misc. minor items

### ISSUE THREAD

**Issue by steven-omaha** [martinco/LazyMDC#13]
Hey Martin, Professor here. In this issue I'm reporting minor items in a combined manner, so that you are not flooded with issues. All items relate to the A-10C.

- ground speed default (350 kts) is too high. recommend 280.
- in the ordnance list, please adjust the remark about A-10CII exclusive ordnance to also include the AGM-65L
- the new default for chaffs and flares are 240 / 240. Their sum must be less than or equal to 480.
- the intraflight primary and secondary freqs are missing the preset indicators
- the SA-19 RWR was changed from "S6" to "19"

Thanks a lot!

**Comment by martinco** [comment]
* Ground Speed: If you think it's bad for you, poor Helos being asked to go 350 
  * I'll make the default GS airframe dependent; and put a warning on Google Earth import to set the airframe before importing to avoid having to reset that (Done)
* AGM-65L: Thanks, didn't update the note when that got added  (Done)
* Flares: 240/240 (Done)
  * I currently don't have any validation on what goes in there
* Intraflight Presets: Correct
  * I figured that since the ATO is varied; 99% of time they'll be manual so no point having the preset
* SA-19 RWR was changed from "S6" to "19": Done

These will be in next update

**Comment by steven-omaha** [comment]
> Ground Speed: If you think it's bad for you, poor Helos being asked to go 350
    I'll make the default GS airframe dependent; and put a warning on Google Earth import to set the airframe before importing to avoid having to reset that (Done)

True :)


> Intraflight Presets: Correct
    I figured that since the ATO is varied; 99% of time they'll be manual so no point having the preset

The ATO gives us frequencies that are radio presets about 90% of the time, so would still be nice to have. (Couldn't judge from your comment if that is already in there, or not)

**Comment by steven-omaha** [comment]
closing this since this is 80% complete, will reopen a new issue for the remaining item. Thanks!
