### ISSUE TITLE
allow for selection of departure and arrival routes

### ISSUE THREAD

**Issue by steven-omaha** [martinco/LazyMDC#17]
For the three items departure, arrival and alternate, add a text field that allows selecting the corresponding procedure (VFR routes like MANSA and LUGAL, straight-in, ILS-31R, PAR, TACAN-31R, ...)

**Comment by martinco** [comment]
They used to exist:

![image](https://user-images.githubusercontent.com/250888/99131477-25774000-260b-11eb-92e7-86995031b77d.png)

However they were removed after discussion in #mdc_development

In summary:

- Departure is given by delivery before startup if ATC present
- If no ATC then Active RW is part of ATIS so that may be unknown when building MDC

As such it would normally have been Per-ATC, and and even then wouldn't make that much difference and would be well within the additional fuel load to change what runway you are heading to I think I'll remove them to keep it simple

Added benefits of less data to manage.

**Comment by steven-omaha** [comment]
Okay, makes sense. Thanks!
