### ISSUE TITLE
F16C: Distance column for Waypoints

### ISSUE THREAD

**Issue by jkhoel** [martinco/LazyMDC#18]
Would it be possible to show the distance between the waypoints on the MDC? I realize real-estate is an issue, but considering the distance should be a max of 3 digits, I think it should fit. Will post reference picture on Discord.

This would allow pilots to check their WPs against another source before the full Alpha-check, as the distance should match up after inputting coordinates, and thus potentially save some time

**Comment by martinco** [comment]
It was indeed removed along with brg for space when font size increased for readability for our VR users. 

I'll add dist and round to int to save 2 characters of width and worst case is folks will just have word wrapping WP names

**Comment by jkhoel** [comment]
Excellent! And for sure - no use splitting the nautical to decimals, that level of accuracy is available inside the aircraft anyway.

Are there maximum character limitations on the WP name fields?

**Comment by martinco** [comment]
No it just word wraps - increasing font sizing has certainly caused some issues with spatial constraints and removing items, but not all of our monitors are the same pixel density and the way DCS draws kneeboards as a fixed size means you're somewhat out of luck and have to compromise 

This is changing soon: https://www.youtube.com/watch?v=g7rJyrtnrFM - so hopefully when we can position / size kneeboards to our own wants rather than to the monitor height we might be  able to adjust the font size down again and still not frustrate VR.

Anyhow since I already save the data, it's a very quick addition :)
