### ISSUE TITLE
Double clicking any previously created waypoint shows outdated coords in "set from string" field

### ISSUE THREAD

**Issue by steven-omaha** [martinco/LazyMDC#30]
Steps to reproduce:
1. For the A-10C, create two waypoints 1 and 2, each with "set from string" with different coordinates.
2. After having created waypoint 2, double click on waypoint 1.

Result: All values in the coordinate section show the representation of waypoint 1. The "set from string" field shows the last used string, which is from waypoint one.

Expected result: Either show nothing in "set from string" (probably easiest), or show the string representation of the double-clicked coordinate.

Reasoning: For flying in any of the ranges I create a flightplan where each corner of the range is a waypoint, so I can see the range outline in the TAD. To create a closed polygon, I need 5 waypoints, where the first and last waypoint are identical. My go to procedure is creating the waypoints from string, and when I arrive at the 5th waypoint, I want to copy the 1st. After having used this field 4 times, I instinctively assume that I can copy waypoints like this. This leads to wrong coordinates in the flightplan.

**Comment by martinco** [comment]
Will do

I'll update it to the the current selected coordinate display format for non-empty coordinates, otherwise empty.

That way it adds a nice copy/paste ability to the view as well

Seems to make the most sense to me, otherwise the question becomes: what format do we use by default (I would lean towards DDM 3dp so it can easily be pasted into CF)
